'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace WebFormsControlls

    Partial Public Class WebControls

        '''<summary>
        '''form1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

        '''<summary>
        '''Label1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''username control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents username As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''Label6 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label6 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''EmailID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents EmailID As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''Label2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label2 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBox2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBox2 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''Label3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label3 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBox3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBox3 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''Label4 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label4 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''RadioButton1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RadioButton1 As Global.System.Web.UI.WebControls.RadioButton

        '''<summary>
        '''RadioButton2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RadioButton2 As Global.System.Web.UI.WebControls.RadioButton

        '''<summary>
        '''Button1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Button1 As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''message control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents message As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ShowUserNameLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ShowUserNameLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ShowUserName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ShowUserName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ShowEmailIDLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ShowEmailIDLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ShowEmail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ShowEmail As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ShowGenderLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ShowGenderLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ShowGender control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ShowGender As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ShowCourseLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ShowCourseLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ShowCourses control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ShowCourses As Global.System.Web.UI.WebControls.Label
    End Class
End Namespace
